#!/usr/bin/env sh
set -eu

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
REPO_DIR="$(CDPATH= cd -- "${SCRIPT_DIR}/.." && pwd)"
ENV_FILE="${ENV_FILE:-${REPO_DIR}/.env}"
EXAMPLE_ENV="${REPO_DIR}/.env.example"

ask_input() {
  prompt="$1"
  default="${2:-}"
  if [ -n "$default" ]; then
    printf "%s [%s]: " "$prompt" "$default"
  else
    printf "%s: " "$prompt"
  fi
  IFS= read -r answer || true
  if [ -z "$answer" ]; then
    printf "%s" "$default"
  else
    printf "%s" "$answer"
  fi
}

ask_yes_no() {
  prompt="$1"
  default="${2:-y}"
  while :; do
    if [ "$default" = "y" ]; then
      printf "%s [Y/n]: " "$prompt"
    else
      printf "%s [y/N]: " "$prompt"
    fi
    IFS= read -r answer || true
    answer="$(printf "%s" "$answer" | tr '[:upper:]' '[:lower:]')"
    if [ -z "$answer" ]; then
      answer="$default"
    fi
    case "$answer" in
      y|yes) return 0 ;;
      n|no) return 1 ;;
      *) echo "Please answer y or n." ;;
    esac
  done
}

need_cmd() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "ERROR: Missing required command: $1"
    exit 1
  }
}

is_truthy() {
  case "$(printf '%s' "${1:-}" | tr '[:upper:]' '[:lower:]')" in
    1|true|yes|on) return 0 ;;
    *) return 1 ;;
  esac
}

csv_has() {
  csv="$1"
  needle="$2"
  old_ifs="$IFS"
  IFS=','
  for item in $csv; do
    clean="$(printf '%s' "$item" | tr -d '[:space:]')"
    if [ "$clean" = "$needle" ]; then
      IFS="$old_ifs"
      return 0
    fi
  done
  IFS="$old_ifs"
  return 1
}

as_sudo() {
  if [ "$(id -u)" -eq 0 ]; then
    "$@"
    return
  fi
  if command -v sudo >/dev/null 2>&1; then
    sudo "$@"
    return
  fi
  echo "ERROR: sudo is required for this operation (or run as root)."
  exit 1
}

ensure_fstab_line() {
  mount_point="$1"
  new_line="$2"
  fstab="/etc/fstab"
  ts="$(date +%Y%m%d%H%M%S)"

  as_sudo cp "$fstab" "${fstab}.bak.${ts}"
  if as_sudo grep -Fq "$mount_point" "$fstab"; then
    as_sudo sed -i "\|$mount_point|d" "$fstab"
  fi
  printf '%s\n' "$new_line" | as_sudo tee -a "$fstab" >/dev/null
}

ensure_absolute_dir() {
  path="$1"
  label="$2"
  if [ -z "$path" ]; then
    echo "ERROR: ${label} is empty."
    exit 1
  fi
  case "$path" in
    /*) ;;
    *)
      echo "ERROR: ${label} must be an absolute path, got: ${path}"
      exit 1
      ;;
  esac
  mkdir -p "$path"
  if [ ! -d "$path" ]; then
    echo "ERROR: Could not create/read directory for ${label}: ${path}"
    exit 1
  fi
}

assert_writable() {
  path="$1"
  label="$2"
  probe="${path}/.fjordlens_write_test.$$"
  if ! ( : > "$probe" ) 2>/dev/null; then
    echo "ERROR: ${label} is not writable: ${path}"
    exit 1
  fi
  rm -f "$probe" >/dev/null 2>&1 || true
}

mount_field() {
  path="$1"
  field="$2"
  findmnt -T "$path" -n -o "$field" 2>/dev/null | head -n 1 || true
}

report_mount() {
  path="$1"
  label="$2"
  expected_csv="$3"
  target="$(mount_field "$path" TARGET)"
  source="$(mount_field "$path" SOURCE)"
  fstype="$(mount_field "$path" FSTYPE)"
  if [ -z "$target" ] || [ -z "$fstype" ]; then
    echo "ERROR: Could not resolve mount info for ${label}: ${path}"
    exit 1
  fi
  echo "    ${label}: ${path}"
  echo "      mount: ${source} on ${target} (fstype=${fstype})"
  if [ -n "$expected_csv" ] && ! csv_has "$expected_csv" "$fstype"; then
    echo "ERROR: ${label} fstype '${fstype}' is not in EXPECT list: ${expected_csv}"
    exit 1
  fi
}

require_runtime_tools() {
  need_cmd docker
  need_cmd findmnt
  docker compose version >/dev/null 2>&1 || {
    echo "ERROR: docker compose plugin not available."
    exit 1
  }
  if is_truthy "${SETUP_NFS_UPLOADS_ENABLED:-0}"; then
    need_cmd grep
    need_cmd sed
    need_cmd tee
    need_cmd mount
  fi
}

load_env_with_defaults() {
  if [ -f "$ENV_FILE" ]; then
    set -a
    # shellcheck disable=SC1090
    . "$ENV_FILE"
    set +a
  fi

  : "${APP_PORT:=9080}"
  : "${DATA_DIR:=/volume1/docker/fjordlens/data}"
  : "${UPLOADS_HOST_DIR:=/volume1/docker/fjordlens/data/uploads}"
  : "${THUMBS_HOST_DIR:=/volume1/docker/fjordlens/data/thumbs}"
  : "${TZ:=Europe/Copenhagen}"
  : "${LOG_LEVEL:=INFO}"
  : "${SQLITE_JOURNAL_MODE:=}"
  : "${SQLITE_BUSY_TIMEOUT_MS:=10000}"
  : "${ENABLE_LIBRARY_SOURCE:=0}"
  : "${ENABLE_SCAN_FEATURES:=0}"
  : "${PHOTOFRAME_TEXT_ONLY:=0}"
  : "${PHOTOFRAME_UPDATE_UPLOAD_MAX_BYTES:=314572800}"
  : "${EXPECT_DATA_FSTYPES:=}"
  : "${EXPECT_UPLOADS_FSTYPES:=}"
  : "${EXPECT_THUMBS_FSTYPES:=}"
  : "${EXPECT_PHOTO_FSTYPES:=}"
  : "${PHOTO_DIR:=/volume1/docker/fjordlens/Photos}"

  : "${SETUP_NFS_UPLOADS_ENABLED:=0}"
  : "${SETUP_NFS_EXPORT:=10.10.0.161:/volume1/ProxmoxFjordlens}"
  : "${SETUP_NFS_MOUNT_ROOT:=${HOME:-/root}/synology/fjordlens-data}"
  : "${SETUP_NFS_UPLOADS_SUBDIR:=uploads}"
  : "${SETUP_NFS_FSTAB_OPTIONS:=vers=3,_netdev,nofail}"
}

write_env_file() {
  target="$1"
  cat > "$target" <<EOF
# Generated by scripts/fresh_setup.sh
APP_PORT=${APP_PORT}
DATA_DIR=${DATA_DIR}
UPLOADS_HOST_DIR=${UPLOADS_HOST_DIR}
THUMBS_HOST_DIR=${THUMBS_HOST_DIR}
TZ=${TZ}
LOG_LEVEL=${LOG_LEVEL}
SQLITE_JOURNAL_MODE=${SQLITE_JOURNAL_MODE}
SQLITE_BUSY_TIMEOUT_MS=${SQLITE_BUSY_TIMEOUT_MS}
ENABLE_LIBRARY_SOURCE=${ENABLE_LIBRARY_SOURCE}
ENABLE_SCAN_FEATURES=${ENABLE_SCAN_FEATURES}
PHOTOFRAME_TEXT_ONLY=${PHOTOFRAME_TEXT_ONLY}
PHOTOFRAME_UPDATE_UPLOAD_MAX_BYTES=${PHOTOFRAME_UPDATE_UPLOAD_MAX_BYTES}
EXPECT_DATA_FSTYPES=${EXPECT_DATA_FSTYPES}
EXPECT_UPLOADS_FSTYPES=${EXPECT_UPLOADS_FSTYPES}
EXPECT_THUMBS_FSTYPES=${EXPECT_THUMBS_FSTYPES}
EXPECT_PHOTO_FSTYPES=${EXPECT_PHOTO_FSTYPES}
# Setup metadata for reruns:
SETUP_NFS_UPLOADS_ENABLED=${SETUP_NFS_UPLOADS_ENABLED}
SETUP_NFS_EXPORT=${SETUP_NFS_EXPORT}
SETUP_NFS_MOUNT_ROOT=${SETUP_NFS_MOUNT_ROOT}
SETUP_NFS_UPLOADS_SUBDIR=${SETUP_NFS_UPLOADS_SUBDIR}
SETUP_NFS_FSTAB_OPTIONS=${SETUP_NFS_FSTAB_OPTIONS}
EOF

  if is_truthy "$ENABLE_LIBRARY_SOURCE"; then
    printf "PHOTO_DIR=%s\n" "$PHOTO_DIR" >> "$target"
  else
    cat >> "$target" <<EOF
# PHOTO_DIR is optional when ENABLE_LIBRARY_SOURCE=0
# PHOTO_DIR=/volume1/docker/fjordlens/Photos
EOF
  fi
}

configure_nfs_upload_mount_if_enabled() {
  if ! is_truthy "${SETUP_NFS_UPLOADS_ENABLED:-0}"; then
    return 0
  fi
  if [ -z "${SETUP_NFS_EXPORT:-}" ] || [ -z "${SETUP_NFS_MOUNT_ROOT:-}" ]; then
    echo "ERROR: NFS setup is enabled but export/mount root is missing."
    exit 1
  fi
  case "$SETUP_NFS_MOUNT_ROOT" in
    /*) ;;
    *)
      echo "ERROR: SETUP_NFS_MOUNT_ROOT must be absolute: ${SETUP_NFS_MOUNT_ROOT}"
      exit 1
      ;;
  esac

  echo
  echo "==> Configuring NFS mount in /etc/fstab"
  as_sudo mkdir -p "$SETUP_NFS_MOUNT_ROOT"
  fstab_line="${SETUP_NFS_EXPORT} ${SETUP_NFS_MOUNT_ROOT} nfs ${SETUP_NFS_FSTAB_OPTIONS} 0 0"
  ensure_fstab_line "$SETUP_NFS_MOUNT_ROOT" "$fstab_line"
  as_sudo mount -a

  if ! findmnt -T "$SETUP_NFS_MOUNT_ROOT" >/dev/null 2>&1; then
    echo "ERROR: NFS mount is not active at ${SETUP_NFS_MOUNT_ROOT}"
    exit 1
  fi
  echo "    NFS mount active: ${SETUP_NFS_MOUNT_ROOT}"
}

run_preflight_and_start() {
  require_runtime_tools
  configure_nfs_upload_mount_if_enabled

  echo
  echo "==> Mount preflight"
  ensure_absolute_dir "$DATA_DIR" "DATA_DIR"
  ensure_absolute_dir "$UPLOADS_HOST_DIR" "UPLOADS_HOST_DIR"
  ensure_absolute_dir "$THUMBS_HOST_DIR" "THUMBS_HOST_DIR"

  mkdir -p "${UPLOADS_HOST_DIR}/originals" "${UPLOADS_HOST_DIR}/converted"

  assert_writable "$DATA_DIR" "DATA_DIR"
  assert_writable "$UPLOADS_HOST_DIR" "UPLOADS_HOST_DIR"
  assert_writable "$THUMBS_HOST_DIR" "THUMBS_HOST_DIR"

  report_mount "$DATA_DIR" "DATA_DIR" "$EXPECT_DATA_FSTYPES"
  report_mount "$UPLOADS_HOST_DIR" "UPLOADS_HOST_DIR" "$EXPECT_UPLOADS_FSTYPES"
  report_mount "$THUMBS_HOST_DIR" "THUMBS_HOST_DIR" "$EXPECT_THUMBS_FSTYPES"

  if is_truthy "$ENABLE_LIBRARY_SOURCE"; then
    if [ -z "${PHOTO_DIR:-}" ]; then
      echo "ERROR: ENABLE_LIBRARY_SOURCE=1 requires PHOTO_DIR in ${ENV_FILE}"
      exit 1
    fi
    if [ ! -d "$PHOTO_DIR" ]; then
      echo "ERROR: PHOTO_DIR does not exist: ${PHOTO_DIR}"
      exit 1
    fi
    report_mount "$PHOTO_DIR" "PHOTO_DIR" "$EXPECT_PHOTO_FSTYPES"
  else
    echo "    PHOTO_DIR check skipped (ENABLE_LIBRARY_SOURCE=${ENABLE_LIBRARY_SOURCE})"
  fi

  echo
  echo "==> Starting containers"
  cd "$REPO_DIR"
  docker compose up -d --build
  echo "==> Done"
  echo "    Open: http://localhost:${APP_PORT:-9080}"
}

if [ "${1:-}" = "--start-only" ]; then
  echo "==> FjordLens start-only mode"
  echo "    Repo: ${REPO_DIR}"
  echo "    Env : ${ENV_FILE}"
  if [ ! -f "$ENV_FILE" ]; then
    echo "ERROR: Missing env file: ${ENV_FILE}"
    echo "Run full wizard first:"
    echo "  sh scripts/fresh_setup.sh"
    exit 1
  fi
  load_env_with_defaults
  run_preflight_and_start
  exit 0
fi

if [ "${1:-}" != "" ]; then
  echo "Usage:"
  echo "  sh scripts/fresh_setup.sh               # guided setup (A-Z)"
  echo "  sh scripts/fresh_setup.sh --start-only  # preflight + optional NFS/fstab + start"
  exit 1
fi

echo "==> FjordLens guided setup"
echo "    Repo: ${REPO_DIR}"
echo "    Env : ${ENV_FILE}"

if [ ! -f "$EXAMPLE_ENV" ]; then
  echo "ERROR: Missing .env.example in repo root."
  exit 1
fi

load_env_with_defaults

echo
echo "Step 1/7: Basic app settings"
APP_PORT="$(ask_input "Web port (APP_PORT)" "$APP_PORT")"
TZ="$(ask_input "Timezone (TZ)" "$TZ")"
LOG_LEVEL="$(ask_input "Log level (LOG_LEVEL)" "$LOG_LEVEL")"

echo
echo "Step 2/7: Optional NFS uploads mount (/etc/fstab)"
if ask_yes_no "Configure NFS mount for uploads in /etc/fstab?" "$(is_truthy "$SETUP_NFS_UPLOADS_ENABLED" && echo y || echo n)"; then
  SETUP_NFS_UPLOADS_ENABLED="1"
  SETUP_NFS_EXPORT="$(ask_input "NFS export (server:/path)" "$SETUP_NFS_EXPORT")"
  SETUP_NFS_MOUNT_ROOT="$(ask_input "Local NFS mount root" "$SETUP_NFS_MOUNT_ROOT")"
  SETUP_NFS_UPLOADS_SUBDIR="$(ask_input "Uploads subdir inside NFS mount" "$SETUP_NFS_UPLOADS_SUBDIR")"
  SETUP_NFS_FSTAB_OPTIONS="$(ask_input "NFS fstab options" "$SETUP_NFS_FSTAB_OPTIONS")"
  SETUP_NFS_UPLOADS_SUBDIR="$(printf "%s" "$SETUP_NFS_UPLOADS_SUBDIR" | sed 's#^/*##; s#/*$##')"
  if [ -z "$SETUP_NFS_UPLOADS_SUBDIR" ]; then
    SETUP_NFS_UPLOADS_SUBDIR="uploads"
  fi
  UPLOADS_HOST_DIR="${SETUP_NFS_MOUNT_ROOT}/${SETUP_NFS_UPLOADS_SUBDIR}"
  if [ -z "$EXPECT_UPLOADS_FSTYPES" ]; then
    EXPECT_UPLOADS_FSTYPES="nfs,nfs4"
  fi
else
  SETUP_NFS_UPLOADS_ENABLED="0"
fi

echo
echo "Step 3/7: Storage paths (host paths)"
DATA_DIR="$(ask_input "DATA_DIR (db/cache/internal state)" "$DATA_DIR")"
UPLOADS_HOST_DIR="$(ask_input "UPLOADS_HOST_DIR (uploads/originals+converted)" "$UPLOADS_HOST_DIR")"
THUMBS_HOST_DIR="$(ask_input "THUMBS_HOST_DIR (thumbnails)" "$THUMBS_HOST_DIR")"

echo
echo "Step 4/7: Optional library source"
if ask_yes_no "Enable separate read-only library source (PHOTO_DIR)?" "$(is_truthy "$ENABLE_LIBRARY_SOURCE" && echo y || echo n)"; then
  ENABLE_LIBRARY_SOURCE="1"
  PHOTO_DIR="$(ask_input "PHOTO_DIR (library source path)" "$PHOTO_DIR")"
else
  ENABLE_LIBRARY_SOURCE="0"
fi

echo
echo "Step 5/7: Feature toggles"
if ask_yes_no "Enable scan/rescan/rethumb UI + endpoints?" "$(is_truthy "$ENABLE_SCAN_FEATURES" && echo y || echo n)"; then
  ENABLE_SCAN_FEATURES="1"
else
  ENABLE_SCAN_FEATURES="0"
fi

echo
echo "Step 6/7: SQLite"
sqlite_choice="$(ask_input "SQLite journal mode (auto/WAL/DELETE/TRUNCATE/PERSIST/MEMORY/OFF)" "${SQLITE_JOURNAL_MODE:-auto}")"
sqlite_choice_lc="$(printf "%s" "$sqlite_choice" | tr '[:upper:]' '[:lower:]')"
if [ "$sqlite_choice_lc" = "auto" ] || [ -z "$sqlite_choice_lc" ]; then
  SQLITE_JOURNAL_MODE=""
else
  SQLITE_JOURNAL_MODE="$(printf "%s" "$sqlite_choice" | tr '[:lower:]' '[:upper:]')"
fi
SQLITE_BUSY_TIMEOUT_MS="$(ask_input "SQLite busy timeout ms" "$SQLITE_BUSY_TIMEOUT_MS")"

echo
echo "Step 7/7: Optional strict mount checks"
if ask_yes_no "Enable strict fs-type checks (NFS/local expectations)?" "$( [ -n "$EXPECT_UPLOADS_FSTYPES$EXPECT_THUMBS_FSTYPES$EXPECT_DATA_FSTYPES$EXPECT_PHOTO_FSTYPES" ] && echo y || echo n )"; then
  EXPECT_UPLOADS_FSTYPES="$(ask_input "EXPECT_UPLOADS_FSTYPES" "${EXPECT_UPLOADS_FSTYPES:-nfs,nfs4}")"
  EXPECT_THUMBS_FSTYPES="$(ask_input "EXPECT_THUMBS_FSTYPES (blank to skip)" "$EXPECT_THUMBS_FSTYPES")"
  EXPECT_DATA_FSTYPES="$(ask_input "EXPECT_DATA_FSTYPES (blank to skip)" "$EXPECT_DATA_FSTYPES")"
  if is_truthy "$ENABLE_LIBRARY_SOURCE"; then
    EXPECT_PHOTO_FSTYPES="$(ask_input "EXPECT_PHOTO_FSTYPES (blank to skip)" "$EXPECT_PHOTO_FSTYPES")"
  else
    EXPECT_PHOTO_FSTYPES=""
  fi
else
  EXPECT_UPLOADS_FSTYPES=""
  EXPECT_THUMBS_FSTYPES=""
  EXPECT_DATA_FSTYPES=""
  EXPECT_PHOTO_FSTYPES=""
fi

if [ -f "$ENV_FILE" ]; then
  backup_file="${ENV_FILE}.bak.$(date +%Y%m%d%H%M%S)"
  cp "$ENV_FILE" "$backup_file"
  echo
  echo "Backup of existing env saved to:"
  echo "  ${backup_file}"
fi

write_env_file "$ENV_FILE"

echo
echo "Wrote configuration:"
echo "  ${ENV_FILE}"
echo
echo "Summary:"
echo "  APP_PORT=${APP_PORT}"
echo "  DATA_DIR=${DATA_DIR}"
echo "  UPLOADS_HOST_DIR=${UPLOADS_HOST_DIR}"
echo "  THUMBS_HOST_DIR=${THUMBS_HOST_DIR}"
echo "  ENABLE_LIBRARY_SOURCE=${ENABLE_LIBRARY_SOURCE}"
if is_truthy "$ENABLE_LIBRARY_SOURCE"; then
  echo "  PHOTO_DIR=${PHOTO_DIR}"
fi
echo "  ENABLE_SCAN_FEATURES=${ENABLE_SCAN_FEATURES}"
echo "  SETUP_NFS_UPLOADS_ENABLED=${SETUP_NFS_UPLOADS_ENABLED}"
if is_truthy "$SETUP_NFS_UPLOADS_ENABLED"; then
  echo "  SETUP_NFS_EXPORT=${SETUP_NFS_EXPORT}"
  echo "  SETUP_NFS_MOUNT_ROOT=${SETUP_NFS_MOUNT_ROOT}"
  echo "  SETUP_NFS_UPLOADS_SUBDIR=${SETUP_NFS_UPLOADS_SUBDIR}"
fi
if [ -n "$SQLITE_JOURNAL_MODE" ]; then
  echo "  SQLITE_JOURNAL_MODE=${SQLITE_JOURNAL_MODE}"
else
  echo "  SQLITE_JOURNAL_MODE=<auto>"
fi

echo
if ask_yes_no "Run preflight + optional NFS/fstab + docker compose up -d --build now?" "y"; then
  run_preflight_and_start
else
  echo "Skipped start."
  echo "Run later with:"
  echo "  sh scripts/fresh_setup.sh --start-only"
fi
