#!/usr/bin/env sh
set -eu

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
REPO_DIR="$(CDPATH= cd -- "${SCRIPT_DIR}/.." && pwd)"
ENV_FILE="${ENV_FILE:-${REPO_DIR}/.env}"
EXAMPLE_ENV="${REPO_DIR}/.env.example"

ask_input() {
  prompt="$1"
  default="${2:-}"
  if [ -n "$default" ]; then
    printf "%s [%s]: " "$prompt" "$default"
  else
    printf "%s: " "$prompt"
  fi
  IFS= read -r answer || true
  if [ -z "$answer" ]; then
    printf "%s" "$default"
  else
    printf "%s" "$answer"
  fi
}

ask_yes_no() {
  prompt="$1"
  default="${2:-y}"
  while :; do
    if [ "$default" = "y" ]; then
      printf "%s [Y/n]: " "$prompt"
    else
      printf "%s [y/N]: " "$prompt"
    fi
    IFS= read -r answer || true
    answer="$(printf "%s" "$answer" | tr '[:upper:]' '[:lower:]')"
    if [ -z "$answer" ]; then
      answer="$default"
    fi
    case "$answer" in
      y|yes) return 0 ;;
      n|no) return 1 ;;
      *) echo "Please answer y or n." ;;
    esac
  done
}

write_env_file() {
  target="$1"
  cat > "$target" <<EOF
# Generated by scripts/setup.sh
APP_PORT=${APP_PORT}
DATA_DIR=${DATA_DIR}
UPLOADS_HOST_DIR=${UPLOADS_HOST_DIR}
THUMBS_HOST_DIR=${THUMBS_HOST_DIR}
TZ=${TZ}
LOG_LEVEL=${LOG_LEVEL}
SQLITE_JOURNAL_MODE=${SQLITE_JOURNAL_MODE}
SQLITE_BUSY_TIMEOUT_MS=${SQLITE_BUSY_TIMEOUT_MS}
ENABLE_LIBRARY_SOURCE=${ENABLE_LIBRARY_SOURCE}
ENABLE_SCAN_FEATURES=${ENABLE_SCAN_FEATURES}
PHOTOFRAME_TEXT_ONLY=${PHOTOFRAME_TEXT_ONLY}
PHOTOFRAME_UPDATE_UPLOAD_MAX_BYTES=${PHOTOFRAME_UPDATE_UPLOAD_MAX_BYTES}
EXPECT_DATA_FSTYPES=${EXPECT_DATA_FSTYPES}
EXPECT_UPLOADS_FSTYPES=${EXPECT_UPLOADS_FSTYPES}
EXPECT_THUMBS_FSTYPES=${EXPECT_THUMBS_FSTYPES}
EXPECT_PHOTO_FSTYPES=${EXPECT_PHOTO_FSTYPES}
EOF

  if [ "$ENABLE_LIBRARY_SOURCE" = "1" ]; then
    printf "PHOTO_DIR=%s\n" "$PHOTO_DIR" >> "$target"
  else
    cat >> "$target" <<EOF
# PHOTO_DIR is optional when ENABLE_LIBRARY_SOURCE=0
# PHOTO_DIR=/volume1/docker/fjordlens/Photos
EOF
  fi
}

echo "==> FjordLens guided setup"
echo "    Repo: ${REPO_DIR}"
echo "    Env : ${ENV_FILE}"

if [ ! -f "$EXAMPLE_ENV" ]; then
  echo "ERROR: Missing .env.example in repo root."
  exit 1
fi

# Load existing env as defaults when available.
if [ -f "$ENV_FILE" ]; then
  set -a
  # shellcheck disable=SC1090
  . "$ENV_FILE"
  set +a
fi

: "${APP_PORT:=9080}"
: "${DATA_DIR:=/volume1/docker/fjordlens/data}"
: "${UPLOADS_HOST_DIR:=/volume1/docker/fjordlens/data/uploads}"
: "${THUMBS_HOST_DIR:=/volume1/docker/fjordlens/data/thumbs}"
: "${TZ:=Europe/Copenhagen}"
: "${LOG_LEVEL:=INFO}"
: "${SQLITE_JOURNAL_MODE:=}"
: "${SQLITE_BUSY_TIMEOUT_MS:=10000}"
: "${ENABLE_LIBRARY_SOURCE:=0}"
: "${ENABLE_SCAN_FEATURES:=0}"
: "${PHOTOFRAME_TEXT_ONLY:=0}"
: "${PHOTOFRAME_UPDATE_UPLOAD_MAX_BYTES:=314572800}"
: "${EXPECT_DATA_FSTYPES:=}"
: "${EXPECT_UPLOADS_FSTYPES:=}"
: "${EXPECT_THUMBS_FSTYPES:=}"
: "${EXPECT_PHOTO_FSTYPES:=}"
: "${PHOTO_DIR:=/volume1/docker/fjordlens/Photos}"

echo
echo "Step 1/6: Basic app settings"
APP_PORT="$(ask_input "Web port (APP_PORT)" "$APP_PORT")"
TZ="$(ask_input "Timezone (TZ)" "$TZ")"
LOG_LEVEL="$(ask_input "Log level (LOG_LEVEL)" "$LOG_LEVEL")"

echo
echo "Step 2/6: Storage paths (host paths)"
DATA_DIR="$(ask_input "DATA_DIR (db/cache/internal state)" "$DATA_DIR")"
UPLOADS_HOST_DIR="$(ask_input "UPLOADS_HOST_DIR (uploads/originals+converted)" "$UPLOADS_HOST_DIR")"
THUMBS_HOST_DIR="$(ask_input "THUMBS_HOST_DIR (thumbnails)" "$THUMBS_HOST_DIR")"

echo
echo "Step 3/6: Optional library source"
if ask_yes_no "Enable separate read-only library source (PHOTO_DIR)?" "$( [ "$ENABLE_LIBRARY_SOURCE" = "1" ] && echo y || echo n )"; then
  ENABLE_LIBRARY_SOURCE="1"
  PHOTO_DIR="$(ask_input "PHOTO_DIR (library source path)" "$PHOTO_DIR")"
else
  ENABLE_LIBRARY_SOURCE="0"
fi

echo
echo "Step 4/6: Feature toggles"
if ask_yes_no "Enable scan/rescan/rethumb UI + endpoints?" "$( [ "$ENABLE_SCAN_FEATURES" = "1" ] && echo y || echo n )"; then
  ENABLE_SCAN_FEATURES="1"
else
  ENABLE_SCAN_FEATURES="0"
fi

echo
echo "Step 5/6: SQLite"
sqlite_choice="$(ask_input "SQLite journal mode (auto/WAL/DELETE/TRUNCATE/PERSIST/MEMORY/OFF)" "${SQLITE_JOURNAL_MODE:-auto}")"
sqlite_choice_lc="$(printf "%s" "$sqlite_choice" | tr '[:upper:]' '[:lower:]')"
if [ "$sqlite_choice_lc" = "auto" ] || [ -z "$sqlite_choice_lc" ]; then
  SQLITE_JOURNAL_MODE=""
else
  SQLITE_JOURNAL_MODE="$(printf "%s" "$sqlite_choice" | tr '[:lower:]' '[:upper:]')"
fi
SQLITE_BUSY_TIMEOUT_MS="$(ask_input "SQLite busy timeout ms" "$SQLITE_BUSY_TIMEOUT_MS")"

echo
echo "Step 6/6: Optional strict mount checks"
if ask_yes_no "Enable strict NFS checks for uploads/thumbs paths?" "$( [ -n "$EXPECT_UPLOADS_FSTYPES$EXPECT_THUMBS_FSTYPES" ] && echo y || echo n )"; then
  EXPECT_UPLOADS_FSTYPES="$(ask_input "EXPECT_UPLOADS_FSTYPES" "${EXPECT_UPLOADS_FSTYPES:-nfs,nfs4}")"
  EXPECT_THUMBS_FSTYPES="$(ask_input "EXPECT_THUMBS_FSTYPES" "${EXPECT_THUMBS_FSTYPES:-nfs,nfs4}")"
  EXPECT_DATA_FSTYPES="$(ask_input "EXPECT_DATA_FSTYPES (optional, leave blank to skip)" "$EXPECT_DATA_FSTYPES")"
  if [ "$ENABLE_LIBRARY_SOURCE" = "1" ]; then
    EXPECT_PHOTO_FSTYPES="$(ask_input "EXPECT_PHOTO_FSTYPES (optional, leave blank to skip)" "$EXPECT_PHOTO_FSTYPES")"
  else
    EXPECT_PHOTO_FSTYPES=""
  fi
else
  EXPECT_UPLOADS_FSTYPES=""
  EXPECT_THUMBS_FSTYPES=""
  EXPECT_DATA_FSTYPES=""
  EXPECT_PHOTO_FSTYPES=""
fi

if [ -f "$ENV_FILE" ]; then
  backup_file="${ENV_FILE}.bak.$(date +%Y%m%d%H%M%S)"
  cp "$ENV_FILE" "$backup_file"
  echo
  echo "Backup of existing env saved to:"
  echo "  ${backup_file}"
fi

write_env_file "$ENV_FILE"

echo
echo "Wrote configuration:"
echo "  ${ENV_FILE}"
echo
echo "Summary:"
echo "  APP_PORT=${APP_PORT}"
echo "  DATA_DIR=${DATA_DIR}"
echo "  UPLOADS_HOST_DIR=${UPLOADS_HOST_DIR}"
echo "  THUMBS_HOST_DIR=${THUMBS_HOST_DIR}"
echo "  ENABLE_LIBRARY_SOURCE=${ENABLE_LIBRARY_SOURCE}"
if [ "$ENABLE_LIBRARY_SOURCE" = "1" ]; then
  echo "  PHOTO_DIR=${PHOTO_DIR}"
fi
echo "  ENABLE_SCAN_FEATURES=${ENABLE_SCAN_FEATURES}"
if [ -n "$SQLITE_JOURNAL_MODE" ]; then
  echo "  SQLITE_JOURNAL_MODE=${SQLITE_JOURNAL_MODE}"
else
  echo "  SQLITE_JOURNAL_MODE=<auto>"
fi

echo
if ask_yes_no "Run preflight + docker compose up -d --build now?" "y"; then
  sh "${SCRIPT_DIR}/bootstrap.sh"
else
  echo "Skipped start."
  echo "Run later with:"
  echo "  sh scripts/bootstrap.sh"
fi
